package com.theatre.domain;

public enum ConstBL {
		LOGIN,ADD_SHOW,DELETE_SHOW,EDIT_SHOW,RETURN_SHOW,ADD_THEATRE,DELETE_THEATRE,EDIT_THEATRE,RETURN_THEATRE,ADD_SCHEDULE,DELETE_SCHEDULE,EDIT_SCHEDULE,RETURN_SCHEDULE,
		ADD_RESERVATIONS,DELETE_RESERVATIONS,EDIT_RESERVATIONS,RETURN_RESERVATIONS,THEATRE_NAMES,RETURN_ID_THEATRE,RETURN_SHOW_COLUMN_NAMES,RETURN_DATA_SHOWS,SHOW_NAMES_COMBOBOX,
}
